package me.d0x6k7.Bot.commands.user;

import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.message.guild.GuildMessageReceivedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;

/**
 * Created by 0x6k7 on 10/21/2021.
 */
public class Help extends ListenerAdapter {
    public String bot_prefix = "/";

    @Override
    public void onGuildMessageReceived (GuildMessageReceivedEvent e) {
        String[] args = e.getMessage().getContentRaw().split(" ");

        if(args[0].equalsIgnoreCase(bot_prefix + "help")) {
            EmbedBuilder builder = new EmbedBuilder();
            builder.setTitle("Help Commands List");
            builder.setDescription("Help commands: ");
            builder.addField("/help", "receives a list of help commands", false);
            builder.addField("/clear", "clears a specific amount of messages", false);
            builder.addField("/userinfo", "fetches user's info", false);
            builder.addField("/serverinfo", "fetches server info", false);
            builder.addField("/github", "fetches github user's info", false);
            builder.addField("/rev", "reverses string", false);
            builder.addField("/b64", "encodes text using Base64", false);
            builder.addField("/b64d", "decodes text using Base64", false);
            builder.addField("/date", "gets the date and time in different countries", false);
            builder.addField("/shutdown", "shutdowns the bot (developer-only feature)", false);
            builder.addField("/isup", "is it down or not?", false);
            builder.addField("/meme", "fetches a random meme/cat/dog/birb from the Web", false);
            builder.addField("/ping", "gets your current ping", false);
            builder.addField("/say", "the bot will repeat what the user said", false);
            builder.addField("/uptime", "gets the bot's uptime", false);
            builder.addField("/guess", "guesser might know the answer", false);
            builder.addField("/filter", "filters an image", false);
            builder.addField("/overlay", "overlays an image", false);
            builder.addField("/dadjoke", "generates dads joke", false);
            builder.addField("/screen", "obtains random screenshot", false);
            builder.setFooter("Generated by " + e.getAuthor().getName(), e.getAuthor().getAvatarUrl());
            e.getChannel().sendMessage(builder.build()).queue();
            System.out.println("User " + e.getAuthor().getName() + ": " + e.getMessage().getContentRaw());
        }
    }
}
